AGGIUNTO CANZONI A PLAYLIST HAIM
```{r}
#gn = get_discography("Taylor Swift")
#gn
# haim = get_discography("HAIM")
# haim
# 
# #https://open.spotify.com/playlist/2YQ23X95fmeMGrBusA6eMC?si=41d904cb20b24466 HAIM playlist
# tracks = haim[["track_id"]] 
# tracks
# tracks2 = paste("spotify:track:", tracks)
# gsub(" ", "", tracks2)
# tracks2
# trackkk = tracks2[100:108]
# gsub(" ", "", trackkk)
# trackkk
# 
# add_tracks_to_playlist("2YQ23X95fmeMGrBusA6eMC", c("spotify:track:3h8mGFJU0OSrMGyOSRF5xH", "spotify:track:4CME3Tezpe79zKGfHElok8", "spotify:track:4bKWnThcRc6jgaJ5BRWlbw",
# "spotify:track:2g92k9vKTmpAUbjvGLA2xq", "spotify:track:4bHG9BbfjobU2C8qrKihiM", "spotify:track:0QOkEthncrdZ7MjHSizaIN",
# "spotify:track:7AKRwTgSV6u5ZPWo9ZG1Wq", "spotify:track:7vH1mNqYypyslKjHBbvwM9", "spotify:track:5hmUsfKGVC4DiNKwyLZ8Aw"))
```

AGGIUNTO CANZONI A PLAYLIST DUA
```{r}
#dua = get_discography("Dua Lipa")
#dua
#https://open.spotify.com/playlist/66HxwLojDKuVgyId8LAZZx?si=dbe1b283632f4519
#https://open.spotify.com/album/0JeyP8r2hBxYIoxXv11XiX?si=qCzgsDQVRNeXBjXGXAmzqw
# fn = get_album_tracks("0JeyP8r2hBxYIoxXv11XiX")
# fn
# tracksFN = fn[["id"]]
# tracksFN
# #https://open.spotify.com/album/0obMz8EHnr3dg6NCUK4xWp?si=NPdOosUnSIyFrqNT0KsmXg
# dual = get_album_tracks("0obMz8EHnr3dg6NCUK4xWp", limit = 25)
# dual
# tracksD = dual[["id"]]
# tracksD
# all = c(tracksFN, tracksD)
# all
# all2 = paste("spotify:track:", all)
# gsub(" ", "", all2)
# 
# add_tracks_to_playlist("66HxwLojDKuVgyId8LAZZx", c("spotify:track:3iYNJX4FTRGlfMQySjlGNr", "spotify:track:2FlcxnvybdwpaMmMhaRtSN", "spotify:track:4Ulqu89XempybuL8ApUeqL",
#  "spotify:track:5UncbfPKpWlxsWWyhmM87l", "spotify:track:41z2bSbbtJ9wiIee4RXdi5", "spotify:track:6boViHmG6c8ubzxTvcMoJY",
#  "spotify:track:6pbKWWP8WwTaP5TbSq1vCA", "spotify:track:5CSKbHjpqborGnlzagyaDo", "spotify:track:4PULMUg3AwudcRCzvVmgXT",
# "spotify:track:3pyodt4pb554dMz8fCv7oi", "spotify:track:4szI7zRh7kLApCSqiB6R7b", "spotify:track:5tFAwDNw4K6KYKCWtta7pe",
# "spotify:track:1diS6nkxMQc3wwC4G1j0bh", "spotify:track:1V4uMdCH6aDZire0vVqnXW", "spotify:track:1IdDtg7GhWfHYEWDymq3d2",
# "spotify:track:4FuZofNMHdtsEdrsqwF3xR", "spotify:track:69GVTnxGmUlF2ymLPL2CEp", "spotify:track:0v2boHmWtxMTD2REGN8MbK",
# "spotify:track:2GPCE96x9Go6acdDt8ex6p", "spotify:track:1Oc6LH83W9huJq6u4ZcWIH", "spotify:track:3NqtXWHYIV3VxdRZ7uJwYZ",
# "spotify:track:3R91ySVDSOjcxpW5PZF394", "spotify:track:2lOuvydCaSk8asn1HxBO9r", "spotify:track:6acdKgBrJoYKbJD6WhG81R",
# "spotify:track:6oVGIxnuwcwZspPEYk2Yb3", "spotify:track:5gvtExjZWlMv62e4aY3KeK", "spotify:track:1IX3aarIbfNW3t2geL0YnL",
# "spotify:track:69bQtJECLLhILFjI7ZC4F1", "spotify:track:43oK4OAWUsRZUDVeHtKI4U", "spotify:track:1LPGXjVWl8EnrnyaOgPpBm",
# "spotify:track:1fF9w1hapJKALsOQ6yTcxg", "spotify:track:5oSHYs4Lqx4YTqBSFbxzQx", "spotify:track:0LMgOEJZ5KmNmqcYv22bpJ",
# "spotify:track:3QNcGTHxCCLoHWKIake7x4", "spotify:track:1yr8bvOuWtDsa6zYBi4lYZ", "spotify:track:1NzY8x7l7RvawESgC1FCQH",
# "spotify:track:6Z3aekpUm3ZvWRe766Y0gQ", "spotify:track:0Aj9mjOpjS2TbgSB6sdXNo", "spotify:track:7jr3iPu4O4bTCVwLMbdU2i",
# "spotify:track:3WVcoF2oKbUPCxyjIkYyHs", "spotify:track:2pRQRG07s3q8amlmjOwPcg", "spotify:track:34fyYYMNkz2WlzGnPePCg9",
# "spotify:track:2BY0p8sKIMmRuVjUTasf9G", "spotify:track:3zUdQ1EJtqr1BaHCYSzLTa"))
```

AGGIUNGO CANZONI A PLAYLIST ANNE MARIE
```{r}
#am = get_discography("Anne-Marie") non va sad
#https://open.spotify.com/album/7lPoGKpCGgdKFAxpudhAH5?si=6cCYWbpVROynghzhH4HJGQ
#am = get_album_tracks("7lPoGKpCGgdKFAxpudhAH5")
##tracksSYM = am[["uri"]]
#tracksSYM
#https://open.spotify.com/playlist/21TtJxdFWEiAYzh3MrLHVw?si=2239f7c21b0343bf
#add_tracks_to_playlist("21TtJxdFWEiAYzh3MrLHVw", c("spotify:track:3xtdJnI5fEMtNB6nDqvwyy", "spotify:track:01BC4Xj5tfsfV8DLDrma7q", "spotify:track:572xshmOviSGH70oPYMCZV",
#"spotify:track:6xVr2J3X0zhEJQz5L0QNAP", "spotify:track:4iiOb1mdmh0PCYI4BZYUU9", "spotify:track:7zRObPOHA0tWMYTAxLudmA",
# "spotify:track:6IQCmIGaOxzjNNcwScETVD", "spotify:track:11z8f8BH1WdIlFI9TNQ9mc", "spotify:track:1s3lN9mJhWzhNIw28SQTuf",
#"spotify:track:2BgEsaKNfHUdlh97KmvFyo", "spotify:track:6jrjTqvniDSdk0jQPrdPIu", "spotify:track:4hGBLGIu8Gbqs6C0gqVEb1",
#"spotify:track:7v3wcfESfRKICfvNFnyn0T", "spotify:track:5wXJJlUlG8ebhGulA7rroU", "spotify:track:4OU3hjKf1mQvkY9YPqXlE4",
#"spotify:track:2UMvrzK3hCP7ftLDHLO9G8", "spotify:track:3fvY2U1AzW0diYF0hnBbKt", "spotify:track:01u9H9ZBX0nFWEw1FLnulL")
#)
```
